schema_version: 1

context:
  name: python3-discogs-client
  version: "2.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/python3_discogs_client-${{ version }}.tar.gz
  sha256: 3f9b2f53c51e6b2fbb1bd59c3120c4a06c3aa04e6c806e7bef68b533077f7a2f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - requests
    - oauthlib
    - python-dateutil

tests:
  - python:
      imports:
        - discogs_client
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Python API client for Discogs
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://github.com/joalla/discogs_client

extra:
  recipe-maintainers:
    - HeavyTony2
