schema_version: 1

context:
  name: python3-discogs-client
  version: "2.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/python3_discogs_client-${{ version }}.tar.gz
  sha256: f588ad0c998d04b72e1eadcde9b353023cae6c4a3af6d81db15029c83eec5df1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - requests
    - oauthlib
    - python-dateutil

tests:
  - python:
      imports:
        - discogs_client
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Python API client for Discogs
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://github.com/joalla/discogs_client

extra:
  recipe-maintainers:
    - HeavyTony2
